name: Rust

on:
  push:

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Check format
        run: cargo fmt -- --check
      - name: Cargo check
        run: cargo check

  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  clippy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings